"""creates Tag, Tag_Item, Resource, and Question table. Creates relationships between Tag, Tag_Item, and Organization

Revision ID: 02d24ca2dcfb
Revises: 1074b376d8df
Create Date: 2018-08-31 12:44:29.553271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d24ca2dcfb'
down_revision = '1074b376d8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resource_name'), 'resource', ['name'], unique=False)
    op.create_index(op.f('ix_resource_type'), 'resource', ['type'], unique=False)
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_tag_type'), 'tag', ['type'], unique=False)
    op.create_table('tag_item',
    sa.Column('tag_item_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_item')
    op.drop_index(op.f('ix_tag_type'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_resource_type'), table_name='resource')
    op.drop_index(op.f('ix_resource_name'), table_name='resource')
    op.drop_table('resource')
    op.drop_table('question')
    # ### end Alembic commands ###
