"""empty message

Revision ID: 0401a0c9fc77
Revises: dbef77ca6f5c
Create Date: 2018-09-13 17:43:02.347001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0401a0c9fc77'
down_revision = 'dbef77ca6f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('organization')

    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ein', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_ein'), 'organization', ['ein'], unique=True)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)

    op.drop_table('profile')
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(length=180), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ein', sa.String(length=60), nullable=True),
    sa.Column('website', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_name'), table_name='organization')
    op.create_index(op.f('ix_organization_ein'), table_name='organization')
    # ### end Alembic commands ###

    op.drop_table('profile')
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(length=180), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
