"""adds buget and staff size to the profile table

Revision ID: 6c031f947c66
Revises: 0401a0c9fc77
Create Date: 2018-09-15 17:14:53.692258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c031f947c66'
down_revision = '0401a0c9fc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_ein', table_name='organization')
    op.create_index(op.f('ix_organization_ein'), 'organization', ['ein'], unique=True)
    op.add_column('profile', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('staff_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'staff_size')
    op.drop_column('profile', 'budget')
    op.drop_index(op.f('ix_organization_ein'), table_name='organization')
    op.create_index('ix_organization_ein', 'organization', ['ein'], unique=False)
    # ### end Alembic commands ###
