"""creates proposal table

Revision ID: b23b10ec5e5c
Revises: 9862b10c0e9e
Create Date: 2018-10-21 00:25:05.248759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23b10ec5e5c'
down_revision = '9862b10c0e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal',
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.Column('date_due', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=64000), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('prop_id')
    )
    op.create_index(op.f('ix_organization_ein'), 'organization', ['ein'], unique=True)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_ein'), table_name='organization')
    op.drop_table('proposal')
    # ### end Alembic commands ###
