"""creates migration folder with db structure

Revision ID: dbef77ca6f5c
Revises: 
Create Date: 2018-08-31 16:20:21.120246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbef77ca6f5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ein', sa.String(length=60), nullable=True),
    sa.Column('website', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_index(op.f('ix_organization_ein'), 'organization', ['ein'], unique=True)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_website'), 'organization', ['website'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resource_name'), 'resource', ['name'], unique=False)
    op.create_index(op.f('ix_resource_type'), 'resource', ['type'], unique=False)
    op.create_table('tag',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_tag_type'), 'tag', ['type'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.resource_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('website', sa.String(length=180), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.String(length=64000), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('tag_item',
    sa.Column('tag_item_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.org_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_item')
    op.drop_table('response')
    op.drop_table('profile')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_tag_type'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_resource_type'), table_name='resource')
    op.drop_index(op.f('ix_resource_name'), table_name='resource')
    op.drop_table('resource')
    op.drop_table('question')
    op.drop_index(op.f('ix_organization_website'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_ein'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
